Repository osquery/osquery-python, pull requests merged in 2019-08, with the labels that each got.

#68 travis: Remove python 3.3 and 3.4 and add 3.7
  .travis.yml
Labels: build/test infrastructure

#67 management: Fix socket fd leak
  osquery/__init__.py
  osquery/management.py
Labels: bug

#70 Add pywin32 for Windows platform
  setup.py
Labels: Windows, bug
